checks:
    javascript: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                    coverage:
                      file: coverage/clover.xml
                      format: clover
